# Author: Milton D'az
# File: una_lions.py
#
# This program spells out UNA Lions with dots

from graphics import *
def main ():
	win = GraphWin('UNA Lions')
	circ = Circle(Point(5, 15), 5)
	circ.setFill('yellow')
	circ.draw (win)
	circ = Circle(Point(5, 25), 5)
	circ.setFill('yellow')
	circ.draw (win)
	circ = Circle(Point(10, 35), 5)
	circ.setFill('yellow')
	circ.draw (win)
	circ = Circle(Point(20, 35), 5)
	circ.setFill('yellow')
	circ.draw (win)
	circ = Circle(Point(25, 25), 5)
	circ.setFill('yellow')
	circ.draw (win)
	circ = Circle(Point(25, 15), 5)
	circ.setFill('yellow')
	circ.draw (win)
	circ = Circle(Point(40, 15), 5)
	circ.setFill('purple')
	circ.draw (win)
	circ = Circle(Point(40, 25), 5)
	circ.setFill('purple')
	circ.draw (win)
	circ = Circle(Point(40, 35), 5)
	circ.setFill('purple')
	circ.draw (win)
	circ = Circle(Point(50, 20), 5)
	circ.setFill('purple')
	circ.draw (win)
	circ = Circle(Point(55, 30), 5)
	circ.setFill('purple')
	circ.draw (win)
	circ = Circle(Point(65, 35), 5)
	circ.setFill('purple')
	circ.draw (win)
	circ = Circle(Point(65, 25), 5)
	circ.setFill('purple')
	circ.draw (win)
	circ = Circle(Point(65, 15), 5)
	circ.setFill('purple')
	circ.draw (win)
	circ = Circle(Point(80, 35), 5)
	circ.setFill('white')
	circ.draw (win)
	circ = Circle(Point(85, 25), 5)
	circ.setFill('white')
	circ.draw (win)
	circ = Circle(Point(90, 15), 5)
	circ.setFill('white')
	circ.draw (win)
	circ = Circle(Point(95, 25), 3)
	circ.setFill('white')
	circ.draw (win)
	circ = Circle(Point(100, 15), 5)
	circ.setFill('white')
	circ.draw (win)
	circ = Circle(Point(105, 25), 5)
	circ.setFill('white')
	circ.draw (win)
	circ = Circle(Point(110, 35), 5)
	circ.setFill('white')
	circ.draw (win)
	circ = Circle(Point(5, 50), 5)
	circ.setFill('gray')
	circ.draw (win)
	circ = Circle(Point(5, 60), 5)
	circ.setFill('gray')
	circ.draw (win)
	circ = Circle(Point(5, 70), 5)
	circ.setFill('gray')
	circ.draw (win)
	circ = Circle(Point(15, 70), 5)
	circ.setFill('gray')
	circ.draw (win)
	circ = Circle(Point(35, 70), 5)
	circ.setFill('gray')
	circ.draw (win)
	circ = Circle(Point(35, 60), 5)
	circ.setFill('gray')
	circ.draw (win)
	circ = Circle(Point(35, 50), 3)
	circ.setFill('gray')
	circ.draw (win)
	circ = Circle(Point(60, 65), 10)
	circ.setFill('gray')
	circ.draw (win)
	circ = Circle(Point(80, 70), 5)
	circ.setFill('gray')
	circ.draw (win)
	circ = Circle(Point(80, 60), 5)
	circ.setFill('gray')
	circ.draw (win)
	circ = Circle(Point(80, 50), 5)
	circ.setFill('gray')
	circ.draw (win)
	circ = Circle(Point(90, 60), 5)
	circ.setFill('gray')
	circ.draw (win)
	circ = Circle(Point(100, 60), 5)
	circ.setFill('gray')
	circ.draw (win)
	circ = Circle(Point(105, 70), 5)
	circ.setFill('gray')
	circ.draw (win)
	circ = Circle(Point(120, 70), 5)
	circ.setFill('gray')
	circ.draw (win)
	circ = Circle(Point(130, 65), 5)
	circ.setFill('gray')
	circ.draw (win)
	circ = Circle(Point(125, 55), 5)
	circ.setFill('gray')
	circ.draw (win)
	circ = Circle(Point(135, 50), 5)
	circ.setFill('gray')
	circ.draw (win)
main()
input("Press the <Enter> key to quit.")